import type { Metadata } from "next";
import "./styles/main.scss";
import ClientProvider from "../redux/ClientProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ClientProvider>
				<body>{children}</body>
			</ClientProvider>
		</html>
	);
}
