import type { Metadata } from "next";
import ClientProvider from "../redux/ClientProvider";
import "./main.scss";
import { NavbarLayout } from "@/layouts/NavbarLayout/NavbarLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<header>
					<NavbarLayout />
				</header>
				<ClientProvider>
					<main>{children}</main>
				</ClientProvider>
			</body>
		</html>
	);
}
